### ISSUE TITLE
Camera shuts down after long inactivity

### ISSUE THREAD

**Issue by spomwii** [markvdb/diybookscanner#5] opened 2012-11-14 20:39 UTC
My cameras shuts down after long inactivity. I always restarts the camera before each scan.

**Comment by markvdb** [comment] 2012-11-14 21:54
This is rather hard for me to reproduce. Can you please check:
- the camera is on AC adapter, not on battery
- the configuration option in the generic Canon menu:
  - switch to Live mode
  - go to menu -> wrench and hammer -> power saving -> auto power down -> set to "off"
  - go to menu -> wrench and hammer -> power saving -> display off -> set to "3 min"

Once these settings are confirmed correct, please time the moment of the shutdown and dump the results here.

**Comment by spomwii** [comment] 2012-12-09 21:45
My first post with the description of the problem is not very accurate. This problem happens after a while when scanning. It has nothing todo with inactivity but the problem is that the camera suddenly shuts down like it would do if you remove the power cable. (the lens stays out and the screen goes black. This can happen after 2 minutes or 20 minutes of scanning.

After this happend I lost my camera in the floor. It was broken so I had to buy a new one. 
When I got the new one the same bug appeared again so I reinstalled the SD card, but the bug was still there.
Then I switched the SD cards between the cameras an suddenly the bug was gone. (did a test with 500+ images).

**Comment by SimonAM** [comment] 2013-01-26 16:24
Ive got the same problem. 
One of the cameras powers down, never both at the same time. 

Also sometimes the cameras get triggered with out me touching the pedal. Sometimes just for one photo, sometimes for several. Maby the two issues are related.

**Comment by markvdb** [comment] 2013-01-26 22:12
Simon,

Please first check and confirm the generic Canon camera firmware is configured correctly as per https://github.com/markvdb/diybookscanner/blob/master/misc/settings.md (like mentioned in the software installation manual).

Triggering without touching the pedal might happen because of the sensitivity of the foot pedal. Make sure to keep those presses short, or it will see two key presses where there is only one. 99% chance this will be the issue with triggering multiple times. There is also a good chance that this might solve the other problem.

AFTER both of these things have been verified, please check if the camera is either:
- shutting down (closing the lens properly)
- or crashing (lens stays open, no reply from camera anymore when trying to connect manually using chdk -> see software installation manual)

**Comment by markvdb** [comment] 2013-01-26 22:29
2013/1/26 SimonAM notifications@github.com

> Ive got the same problem.
> One of the cameras powers down, never both at the same time.
> - Is this always the same camera powering down?
- How are your usb devices connected? Are there any other usb devices
  connected?
- Are you running Debian or Ubuntu in a virtual machine?

## Mark

Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by markvdb** [comment] 2013-01-28 10:52
Also have a look at what I added to https://github.com/markvdb/diybookscanner/wiki/Software-triggering-on-Debian-GNU-Linux ...

**Comment by spomwii** [comment] 2013-01-28 10:55
Hi Simon,

I reinstalled CHDK on the camera that was always shutting down and it got better but one of the cameras is still "crashing" from time to time after inactivity. I have made a rule for myself to always power off/on the cameras when I start a new scan or after inactivity. If I do that I never get any problems.

**Comment by SimonAM** [comment] 2013-02-03 19:21
Now i have swapped the memory cards. And made sure the settings are alright. It still crashes.
Its always the right camera, it crashes leaving the lens open. 
It might have something to do with the memory cards. First photo on newely cleansed memory card takes a while to save (earlier for left camera, after the memory card swap it is always the right camera), which i now take into consideration which means not taking the first 2 photos directly after eachother. 
Im running ubuntu 12.04 LTS and there are no other USB-devices connected. 

Somtimes its like the pedal gets stuck, but after i tap the pedal the cameras stop reacting, they crash leaving the lens out. So i reboot and download/delete, then reboot and continue scanning. (the latest 700 page book was scanned in 13 parts due to the right camera crashing) After finishing ill make another scan of the pages completely out of focus, the auto-focus seems to have some problems from time to time. 

All things above are of course annoying and time consuming but the scanner would still be usable if i could just get good image quality. 

I started out with a plain sheet of glass, because of the reflections I bought the "cheaper" anti-glare glass, 2mm. It broke after 700 pages, and even though hardly detectable by the eye when pressing the paper onto the glass, the small "grains" really stands out in the pictures. The more expensive glass with 99% shine-through costs me more than 40 euro per sheet so thats just not going to happen. 

The image quality is poor, and it cant be all because of the glass. So which are the best settings regarding shutter time, auto-focus and lightning settings? 

Best Regards
Simon

**Comment by markvdb** [comment] 2013-02-04 00:20
Hi Simon,

This looks like a faulty or at least performing under spec memory card to
me. Can you please dive into the script, up the time between shots and see
if that makes things operate more reliably?

Mark

Op zondag 3 februari 2013 schreef SimonAM (notifications@github.com) het
volgende:

> Now i have swapped the memory cards. And made sure the settings are
> alright. It still crashes.
> Its always the right camera, it crashes leaving the lens open.
> It might have something to do with the memory cards. First photo on
> newely cleansed memory card takes a while to save (earlier for left camera,
> after the memory card swap it is always the right camera), which i now take
> into consideration which means not taking the first 2 photos directly after
> eachother.
> Im running ubuntu 12.04 LTS and there are no other USB-devices connected.
> 
> Somtimes its like the pedal gets stuck, but after i tap the pedal the
> cameras stop reacting, they crash leaving the lens out. So i reboot and
> download/delete, then reboot and continue scanning. (the latest 700 page
> book was scanned in 13 parts due to the right camera crashing) After
> finishing ill make another scan of the pages completely out of focus, the
> auto-focus seems to have some problems from time to time.
> 
> All things above are of course annoying and time consuming but the
> scanner would still be usable if i could just get good image quality.
> 
> I started out with a plain sheet of glass, because of the reflections I
> bought the "cheaper" anti-glare glass, 2mm. It broke after 700 pages, and
> even though hardly detectable by the eye when pressing the paper onto the
> glass, the small "grains" really stands out in the pictures. The more
> expensive glass with 99% shine-through costs me more than 40 euro per sheet
> so thats just not going to happen.
> 
> The image quality is poor, and it cant be all because of the glass. So
> which are the best settings regarding shutter time, auto-focus and
> lightning settings?
> 
> Best Regards
> Simon
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by markvdb** [comment] 2013-02-04 00:35
> I started out with a plain sheet of glass
> Best budget option.
> 
> because of the reflections I bought the "cheaper" anti-glare glass, 2mm.
> Don't, as per the wiki instructions! Both are guaranteed to bring you
> problems!
> 
> The more expensive glass with 99% shine-through costs me more than 40
> euro per sheet so thats just not going to happen.
> Worth the extra image quality. Alternative, as per the wiki, is to move the
> lamp further away from the subject in some way.
> 
> The image quality is poor, and it cant be all because of the glass.
> It mostly is. Another weak point we discovered is lighting intensity. After
> solving reflections,more light from further away can really help. Daylight
> also. It will allow you faster shutter speeds, which allow sharper shots.
> 
> So which are the best settings regarding shutter time, auto-focus and
> lightning settings?
> Lower shutter time, after you solve reflection and upgrade to stronger
> lighting.

Some form of focus lock will also help.

Mark

> Best Regards
> Simon
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by SimonAM** [comment] 2013-02-04 08:39
As always thanks for the quick answers. 
Ill Try with daylight and shorter shutter speeds on the regular glass. 
Ill try to lock the auro-focus as per your instructions
I don't know what to do to lengthen the time between shots. I can program my own alarm clock, thats it. 
Will i need to format the memory card in a specific way or can i just copy everything from the old memory card to a new one?

Kind Regards
Simon

**Comment by SimonAM** [comment] 2013-02-12 19:56
I have followed your instreuctions for auto focus which led to that i updated the auto-focus issue.

Yes it must be the memory card, i swapped memory cards back and forth. It is always the camera with that memory card that takes much more time saving the pictures. The faulty memory card also get filled with thumbnails. 
However i still dont know what to do about it,.

**Comment by markvdb** [comment] 2013-02-12 20:12
Simon, everything seems to suggest that you got an sd card that even id labelled as class 10 is not really class 10 or faulty. We did sime functionality tests with your card before sending it out, but no dedicated speed test.

This clearly shows that we need a good test for sd card write speed. We don't have one yet.

If acceptable to you, I would like to work on that before sending you another card. That way I can make sure any card sent out is working correctly. In the mean time, you could dive into the triggering script and make it wait for 2.5 or 3 seconds instead of 2. If it is only a performance problem, that might be enough to tenporarily akleviate the problem before we exchange your card.

**Comment by markvdb** [comment] 2013-04-26 22:47
Opened separate issue for sd card speed test.

**Closed as completed by markvdb** 2013-04-26 22:47 UTC
Labels: bug

**Comment by SimonAM** [comment] 2013-08-30 09:43
Hello Mark

There has been over half a year and i still haven't got a new SDcard. 
Please prioritize this higher. 
Even if i think its not my responsibility, i can pay for the card.
I really need the scanner working right now

Simon

Date: Tue, 12 Feb 2013 12:12:39 -0800

**Comment by SimonAM** [comment] 2013-08-30 09:47
Also, the speed of the card is not the biggest problem. 
It is that the carmeras cant erase the thumbnails from it properly.
Which is a fault within the card as the other card is working fine. 

Simon

From: mattsson_648@hotmail.com
To: reply@reply.github.com
Subject: RE: [diybookscanner] Camera shuts down after long inactivity (#5)
Date: Fri, 30 Aug 2013 11:43:04 +0200

Hello Mark

There has been over half a year and i still haven't got a new SDcard. 
Please prioritize this higher. 
Even if i think its not my responsibility, i can pay for the card.
I really need the scanner working right now

Simon

Date: Tue, 12 Feb 2013 12:12:39 -0800

**Comment by markvdb** [comment] 2013-09-05 12:04
Hello Simon,

I have seen your request. We will send you a replacement sd card in the
course of next week.

Kind regards,

Mark

2013/8/30 SimonAM notifications@github.com

> Hello Mark
> 
> There has been over half a year and i still haven't got a new SDcard.
> Please prioritize this higher.
> Even if i think its not my responsibility, i can pay for the card.
> I really need the scanner working right now
> 
> Simon
> 
> Date: Tue, 12 Feb 2013 12:12:39 -0800
> From: notifications@github.com
> To: diybookscanner@noreply.github.com
> CC: mattsson_648@hotmail.com
> Subject: Re: [diybookscanner] Camera shuts down after long inactivity (#5)
> 
> Simon, everything seems to suggest that you got an sd card that even id
> labelled as class 10 is not really class 10 or faulty. We did sime
> functionality tests with your card before sending it out, but no dedicated
> speed test.
> 
> This clearly shows that we need a good test for sd card write speed. We
> don't have one yet.
> 
> If acceptable to you, I would like to work on that before sending you
> another card. That way I can make sure any card sent out is working
> correctly. In the mean time, you could dive into the triggering script and
> make it wait for 2.5 or 3 seconds instead of 2. If it is only a performance
> problem, that might be enough to tenporarily akleviate the problem before
> we exchange your card.
> 
> —
> 
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/markvdb/diybookscanner/issues/5#issuecomment-23550752
> .

## 

Mark Van den Borre
Hogestraat 16
3000 Leuven, België
+32 486 961726

**Comment by SimonAM** [comment] 2013-09-05 12:52
Hi!

Thank you very much!

Also, some interesting facts regarding the faulty SD-card:

There is a hidden trash-folder that is only accessible through the cameras file explorer which means that as the faulty SD-card cant remove the pictures by itself you have to delete the manually. And finally you have to empty the hidden trash bin or else the SD-card will still be full. 
I myself dont understand what this means, but maby it can be of interest for you in your future development of the product. 

Kind regards,

Simon

Date: Thu, 5 Sep 2013 05:04:21 -0700
